version: '3.7'

services:

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_PID=Standard
    - SA_PASSWORD=Password123321
    - MSSQL_AGENT_ENABLED=true

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
    - zookeeper
    - sqlserver
    ports:
    - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1

  connector:
    image: debezium/connect:latest
    ports:
    - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
    - zookeeper
    - sqlserver
    - kafka
